name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: |
        echo "Starting deployment process..."
        echo "DEBUG: Checking deployment status..."
        echo "Deployment completed!"
