name: Generate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docs
      run: |
        echo "Generating documentation..."
        echo "Documentation generated!"
